default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>

development:
  <<: *default
  database: lead_extractor_development

test:
  <<: *default
  database: lead_extractor_test

production:
  <<: *default
  database: lead_extractor_production
  username: lead_extractor
  password: <%= ENV["LEAD_EXTRACTOR_DATABASE_PASSWORD"] %>
